baseurl = "https://annieblog.netlify.com/"
languageCode = "en-us"
title = "Anne's Blog"
# Define how many pages appear per site
paginate = 10

theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Anne Borofski"
    site_description = "Anne's Data Science Blog"
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/BlogProfile.jpg"
    header_background = "img/MercyhurstPic.jpg"
    header_title = "Anne's Data Science Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
 
    github    = "anneborofski"
   
